owner: IronCoreLabs
repo: upptime

sites:
- name: Web site
  url: https://ironcorelabs.com/
- name: IronCore Identity service
  url: https://api.ironcorelabs.com/api/health
- name: Admin Console
  url: https://admin.ironcorelabs.com/api/health
- name: Config Broker
  url: https://config.ironcorelabs.com/health
- name: Config Broker (static content)
  url: https://config.ironcorelabs.com/static/kms/aws/awsRegion.png
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.ironcorelabs.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "IronCore Labs status page"
  introMessage: ""
  navbar:
  - title: Status
    href: /
  - title: GitHub
    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
