name: Add Slack Reminder Label to Issue

on:
  issues:
    types: [opened]

jobs:
  add-issue-label:
    if: github.event.issue.user.name == 'leeroy-travis'
    runs-on: ubuntu-latest
    steps:
      - name: Add tracking label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.WORKFLOW_PAT }}
          labels: slack-reminder
